#!/bin/bash

#clear
clear

# Remove scroll buffer
echo -e  '\0033\0143'

#color
txtbld=$(tput bold)             #  Bold
bldred=${txtbld}$(tput setaf 1) #  red
bldgrn=${txtbld}$(tput setaf 2) #  green
bldcya=${txtbld}$(tput setaf 6) #  cyan

#variables
dir=`pwd`

#functions
pause()
{
echo "${bldgrn} Successfully Installed."
echo ""
read -s -n 1 -p "Press any key to continue...";
}
bootstrap(){
cp -rf $dir/components/css/bootstrap.min.css $dir/$name/assets/css
cp -rf $dir/components/fonts/boot/* $dir/$name/assets/fonts
cp -rf $dir/components/js/bootstrap.min.js $dir/$name/assets/js
cp -rf $dir/components/js/jquery.min.js $dir/$name/assets/js
sed -i '/<!--imports-->/a <link href="assets/css/bootstrap.min.css" rel="stylesheet">\n<script src="assets/js/jquery.min.js"></script>\n<script src="assets/js/bootstrap.min.js"></script>' $dir/$name/index.html
pause
clear
banner
framework-selector
}
semantic(){
cp -rf $dir/components/css/semantic.min.css $dir/$name/assets/css
cp -rf $dir/components/js/semantic.min.js $dir/$name/assets/js
cp -rf $dir/components/js/jquery.min.js $dir/$name/assets/js
sed -i '/<!--imports-->/a <link href="assets/css/semantic.min.css" rel="stylesheet">\n<script src="assets/js/semantic.min.js"></script>\n<script src="assets/js/jquery.min.js"></script>' $dir/$name/index.html
pause
clear
banner
framework-selector
}
animate(){
cp -rf $dir/components/css/animate.min.css $dir/$name/assets/css
sed -i '/<!--imports-->/a <link href="assets/css/animate.min.css" rel="stylesheet">' $dir/$name/index.html
pause
clear
banner
framework-selector
}
pure(){
cp -rf $dir/components/css/pure.min.css $dir/$name/assets/css
sed -i '/<!--imports-->/a <link href="assets/css/pure.min.css" rel="stylesheet">' $dir/$name/index.html
pause
clear
banner
framework-selector
}
mui(){
cp -rf $dir/components/css/mui.min.css $dir/$name/assets/css
cp -rf $dir/components/js/mui.min.js $dir/$name/assets/js
sed -i '/<!--imports-->/a <link href="assets/css/mui.min.css" rel="stylesheet">\n<script src="assets/js/mui.min.js"></script>' $dir/$name/index.html
pause
clear
banner
framework-selector
}
jquery(){
cp -rf $dir/components/js/jquery.min.js $dir/$name/assets/js
sed -i '/<!--imports-->/a <script src="assets/js/jquery.min.js"></script>' $dir/$name/index.html
pause
clear
banner
framework-selector
}
materialize-css(){
cp -rf $dir/components/css/materialize.min.css $dir/$name/assets/css
cp -rf $dir/components/js/materialize.min.js $dir/$name/assets/js
sed -i '/<!--imports-->/a <link href="assets/css/materialize.min.css" rel="stylesheet">\n<script src="assets/js/mmaterialize.min.js"></script>' $dir/$name/index.html
pause
clear
banner
framework-selector
}
mdl(){
cp -rf $dir/components/css/mdl.min.css $dir/$name/assets/css
cp -rf $dir/components/js/mdl.min.js $dir/$name/assets/js
sed -i '/<!--imports-->/a <link href="assets/css/mdl.min.css" rel="stylesheet">\n<script src="assets/js/mdl.min.js"></script>' $dir/$name/index.html
pause
clear
banner
framework-selector
}
fa(){
cp -rf $dir/components/fonts/fa/* $dir/$name/assets/fonts
cp -rf $dir/components/css/font-awesome.min.css $dir/$name/assets/css
sed -i '/<!--imports-->/a <link href="assets/css/font-awesome.min.css" rel="stylesheet">' $dir/$name/index.html
pause
clear
banner
framework-selector
}
mdl-icon(){
cp -rf $dir/components/fonts/mdl/* $dir/$name/assets/fonts
cp -rf $dir/components/css/mdl-icon.min.css $dir/$name/assets/css
sed -i '/<!--imports-->/a <link href="assets/css/mdl-icon.min.css" rel="stylesheet">' $dir/$name/index.html
pause
clear
banner
framework-selector
}

framework-selector()
{
echo -e "${bldgrn}Select any Framework to install"
echo "${bldcya}"
echo -e "1. Bootstrap"
echo -e "2. Material Design Lite"
echo -e "3. MUI CSS"
echo -e "4. Materialize CSS"
echo -e "5. Semantic UI"
echo -e "6. Animate CSS"
echo -e "7. Pure CSS"
echo -e "8. Material Design Icons"
echo -e "9. Font Awesome"
echo -e "10. JQuery"
echo ""
read framework
case $framework in
    1)bootstrap;;
    2)mdl;;
    3)mui;;
    4)materialize-css;;
    5)semantic;;
    6)animate;;
    7)pure;;
    8)mdl-icon;;
    9)fa;;
    10)jquery;;
    *)exit;;
esac
}
app-name(){
echo -e "${bldgrn}Enter the name of your web app:"
echo "${bldcya}"
read name
rm -rf $dir/$name
mkdir $dir/$name
cp -rf $dir/template/* $dir/$name
clear
banner
framework-selector
}
banner(){
echo "${bldred}                           ___       _ _   _       _ _ _____     ";
echo "                          |_ _|_ __ (_) |_(_) __ _| (_)__  /_ __ ";
echo "                           | || '_ \| | __| |/ _\` | | | / /| '__|";
echo "                           | || | | | | |_| | (_| | | |/ /_| |   ";
echo "                          |___|_| |_|_|\__|_|\__,_|_|_/____|_|   ";
echo "                                                                 ";
}
banner
app-name

